name: TWRP Builder

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Repo
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Sync TWRP Source
        run: |
          repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-14.0 --depth=1
          repo sync -j4 --force-sync --no-clone-bundle --no-tags

      - name: Clone Device Trees
        run: |
          git clone https://github.com/Omargamal7/twrp_device_samsung_a26xs -b lineage-20 device/samsung/a26xs
          git clone https://github.com/Omargamal7/twrp_device_samsung_s5e8825-common -b lineage-20 device/samsung/s5e8825-common
          git clone https://github.com/Omargamal7/android_kernel_samsung_universal8825 -b lineage-20 kernel/samsung/s5e8825
          git clone https://github.com/Omargamal7/proprietary_vendor_samsung_universal8825-common -b lineage-20 vendor/samsung

      - name: Build TWRP
        run: |
          export ALLOW_MISSING_DEPENDENCIES=true
          source build/envsetup.sh
          lunch twrp_a26xs-eng
          make recoveryimage -j$(nproc)

      - name: Upload Recovery Image
        uses: actions/upload-artifact@v3
        with:
          name: twrp-a26xs.img
          path: out/target/product/a26xs/recovery.img
