name: Build TWRP (a26xs)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y bc bison build-essential ccache clang flex git \
            libncurses-dev libssl-dev lzop openjdk-11-jdk python3 python3-pip repo unzip zip

      - name: Setup repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo 'export PATH=~/bin:$PATH' >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Initialize repo manifest
        run: |
          repo init -u https://github.com/OmarG-a26/manifest.git -b main

      - name: Sync repo
        run: repo sync -c --no-tags --no-clone-bundle -j$(nproc)

      - name: Setup environment and build
        run: |
          source build/envsetup.sh
          lunch omni_a26xs-eng
          mka recoveryimage

      - name: Upload recovery image
        uses: actions/upload-artifact@v3
        with:
          name: twrp_recovery
          path: out/target/product/a26xs/recovery.img
