name: TWRP Builder (a26xs)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Build Tools
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          git-core repo python3 python3-pip clang \
          libncurses-dev libxml2-utils lzop zlib1g-dev \
          bc flex bison ccache zip unzip curl

    - name: Install Repo Tool
      run: |
        mkdir -p ~/bin
        curl -o ~/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
        chmod +x ~/bin/repo
        echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
        source ~/.bashrc

    - name: Initialize Repo
      run: |
        mkdir -p ~/twrp
        cd ~/twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-14
      env:
        PYTHONWARNINGS: "ignore"

    - name: Sync Source Code
      run: |
        cd ~/twrp
        repo sync -j$(nproc) --force-sync --no-clone-bundle

    - name: Clone Device Trees
      run: |
        cd ~/twrp
        git clone https://github.com/Omargamal7/twrp_device_samsung_a26xs -b lineage-20 device/samsung/a26xs
        git clone https://github.com/Omargamal7/twrp_device_samsung_s5e8825-common -b lineage-20 device/samsung/s5e8825-common
        git clone https://github.com/Omargamal7/android_kernel_samsung_universal8825 -b lineage-20 kernel/samsung/s5e8825
        git clone https://github.com/Omargamal7/proprietary_vendor_samsung_universal8825-common -b lineage-20 vendor/samsung

    - name: Build TWRP
      run: |
        cd ~/twrp
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch twrp_a26xs-eng
        make -j$(nproc) recoveryimage

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: twrp-recovery
        path: ~/twrp/out/target/product/a26xs/recovery.img
