name: TWRP Builder (a26x)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      actions: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Build Environment
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
        git-core python3 clang ccache \
        libncurses-dev libxml2-utils lzop \
        zlib1g-dev libssl-dev bc flex bison

    - name: Install Repo Tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo 'export PATH="$HOME/bin:$PATH"' >> ~/.bashrc
        source ~/.bashrc

    - name: Initialize Repo
      run: |
        mkdir twrp
        cd twrp
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1
      env:
        PYTHONWARNINGS: "ignore"

    - name: Sync Source Code
      run: |
        cd twrp
        repo sync -j4 --force-sync --no-clone-bundle --no-tags

    - name: Clone Device Specifics
      run: |
        cd twrp
        git clone https://github.com/Omargamal7/twrp_device_samsung_a26xs -b lineage-20 device/samsung/a26xs
        git clone https://github.com/Omargamal7/twrp_device_samsung_s5e8825-common -b lineage-20 device/samsung/s5e8825-common
        git clone https://github.com/Omargamal7/android_kernel_samsung_universal8825 -b lineage-20 kernel/samsung/s5e8825
        git clone https://github.com/Omargamal7/proprietary_vendor_samsung_universal8825-common -b lineage-20 vendor/samsung

    - name: Build TWRP Recovery
      run: |
        cd twrp
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch twrp_a26xs-eng
        make -j$(nproc) recoveryimage

    - name: Upload Recovery Image
      uses: actions/upload-artifact@v4
      with:
        name: twrp-a26xs
        path: |
          twrp/out/target/product/a26xs/recovery.img
          twrp/out/target/product/a26xs/recovery.img.sha256sum
